#!/bin/bash

./html2myst.py _source_html/BAlert.html kits/interface/alert.md
./html2myst.py _source_html/BApplication.html kits/application/application.md
./html2myst.py _source_html/BAppFileInfo.html kits/storage/app-file-info.md
./html2myst.py _source_html/BBitmap.html kits/interface/bitmap.md
./html2myst.py _source_html/BBox.html kits/interface/box.md
./html2myst.py _source_html/BBufferConsumer.html kits/media/buffer-consumer.md
./html2myst.py _source_html/BBufferGroup.html kits/media/buffer-group.md
./html2myst.py _source_html/BBuffer.html kits/media/buffer.md
./html2myst.py _source_html/BBufferProducer.html kits/media/buffer-producer.md
./html2myst.py _source_html/BButton.html kits/interface/button.md
./html2myst.py _source_html/BCheckBox.html kits/interface/check-box.md
./html2myst.py _source_html/BCheckBox.html kits/interface/checkbox.md
./html2myst.py _source_html/BClipboard.html kits/application/clipboard.md
./html2myst.py _source_html/BColorControl.html kits/interface/color-control.md
./html2myst.py _source_html/BContinuousParameter.html kits/media/continuous-parameter.md
./html2myst.py _source_html/BControl.html kits/interface/control.md
./html2myst.py _source_html/BControllable.html kits/media/controllable.md
./html2myst.py _source_html/BCursor.html kits/application/cursor.md
./html2myst.py _source_html/BDirectory.html kits/storage/directory.md
./html2myst.py _source_html/BDirectWindow.html kits/game/direct-window.md
./html2myst.py _source_html/BDiscreteParameter.html kits/media/discrete-parameter.md
./html2myst.py _source_html/BDragger.html kits/interface/dragger.md
./html2myst.py _source_html/BEntry.html kits/storage/entry.md
./html2myst.py _source_html/BEntryList.html kits/storage/entry-list.md
./html2myst.py _source_html/BFileGameSound.html kits/game/file-game-sound.md
./html2myst.py _source_html/BFile.html kits/storage/file.md
./html2myst.py _source_html/BFileInterface.html kits/media/file-interface.md
./html2myst.py _source_html/BFilePanel.html kits/storage/file-panel.md
./html2myst.py _source_html/BFont.html kits/interface/font.md
./html2myst.py _source_html/BGLView.html kits/opengl/gl-view.md
./html2myst.py _source_html/BHandler.html kits/application/handler.md
./html2myst.py _source_html/BInputDevice.html kits/input/input-device.md
./html2myst.py _source_html/BInputServerDevice.html kits/input/input-server-device.md
./html2myst.py _source_html/BInputServerFilter.html kits/input/input-server-filter.md
./html2myst.py _source_html/BInputServerMethod.html kits/input/input-server-method.md
./html2myst.py _source_html/BInvoker.html kits/application/invoker.md
./html2myst.py _source_html/BJoystick.html kits/device/joystick.md
./html2myst.py _source_html/BListItem.html kits/interface/list-item.md
./html2myst.py _source_html/BLooper.html kits/application/looper.md
./html2myst.py _source_html/BMailMessage.html kits/mail/mail-message.md
./html2myst.py _source_html/BMediaAddOn.html kits/media/media-add-on.md
./html2myst.py _source_html/BMediaBufferDecoder.html kits/media/media-buffer-decoder.md
./html2myst.py _source_html/BMediaBufferEncoder.html kits/media/media-buffer-encoder.md
./html2myst.py _source_html/BMediaDecoder.html kits/media/media-decoder.md
./html2myst.py _source_html/BMediaEncoder.html kits/media/media-encoder.md
./html2myst.py _source_html/BMediaEventLooper.html kits/media/media-event-looper.md
./html2myst.py _source_html/BMediaFile.html kits/media/media-file.md
./html2myst.py _source_html/BMediaFiles.html kits/media/media-files.md
./html2myst.py _source_html/BMediaFormats.html kits/media/media-formats.md
./html2myst.py _source_html/BMediaNode.html kits/media/media-node.md
./html2myst.py _source_html/BMediaRoster.html kits/media/media-roster.md
./html2myst.py _source_html/BMediaTheme.html kits/media/media-theme.md
./html2myst.py _source_html/BMediaTrack.html kits/media/media-track.md
./html2myst.py _source_html/BMenuBar.html kits/interface/menu-bar.md
./html2myst.py _source_html/BMenuField.html kits/interface/menu-field.md
./html2myst.py _source_html/BMenu.html kits/interface/menu.md
./html2myst.py _source_html/BMenuItem.html kits/interface/menu-item.md
./html2myst.py _source_html/BMessageFilter.html kits/application/message-filter.md
./html2myst.py _source_html/BMessage.html kits/application/message-new.md
./html2myst.py _source_html/BMessageQueue.html kits/application/message-queue.md
./html2myst.py _source_html/BMessenger.html kits/application/messenger.md
./html2myst.py _source_html/BMimeType.html kits/storage/mime-type.md
./html2myst.py _source_html/BNetAddress.html kits/network/net-address.md
./html2myst.py _source_html/BNetBuffer.html kits/network/net-buffer.md
./html2myst.py _source_html/BNetDebug.html kits/network/net-debug.md
./html2myst.py _source_html/BNetEndpoint.html kits/network/net-endpoint.md
./html2myst.py _source_html/BNode.html kits/storage/node.md
./html2myst.py _source_html/BNodeInfo.html kits/storage/node-info.md
./html2myst.py _source_html/BNullParameter.html kits/media/null-parameter.md
./html2myst.py _source_html/BOutlineListView.html kits/interface/outline-list-view.md
./html2myst.py _source_html/BParameterGroup.html kits/media/parameter-group.md
./html2myst.py _source_html/BParameter.html kits/media/parameter.md
./html2myst.py _source_html/BParameterWeb.html kits/media/parameter-web.md
./html2myst.py _source_html/BPath.html kits/storage/path.md
./html2myst.py _source_html/BPictureButton.html kits/interface/picture-button.md
./html2myst.py _source_html/BPicture.html kits/interface/picture.md
./html2myst.py _source_html/BPoint.html kits/interface/point.md
./html2myst.py _source_html/BPolygon.html kits/interface/polygon.md
./html2myst.py _source_html/BPopUpMenu.html kits/interface/pop-up-menu.md
./html2myst.py _source_html/BPrintJob.html kits/interface/print-job.md
./html2myst.py _source_html/BPropertyInfo.html kits/application/property-info.md
./html2myst.py _source_html/BPushGameSound.html kits/game/push-game-sound.md
./html2myst.py _source_html/BQuery.html kits/storage/query.md
./html2myst.py _source_html/BRadioButton.html kits/interface/radio-button.md
./html2myst.py _source_html/BRect.html kits/interface/rect.md
./html2myst.py _source_html/BRefFilter.html kits/storage/ref-filter.md
./html2myst.py _source_html/BRegion.html kits/interface/region.md
./html2myst.py _source_html/BResources.html kits/storage/resources.md
./html2myst.py _source_html/BRoster.html kits/application/roster.md
./html2myst.py _source_html/BScreen.html kits/interface/screen.md
./html2myst.py _source_html/BScrollBar.html kits/interface/scroll-bar.md
./html2myst.py _source_html/BScrollView.html kits/interface/scroll-view.md
./html2myst.py _source_html/BSeparatorItem.html kits/interface/separator-item.md
./html2myst.py _source_html/BSerialPort.html kits/device/serial-port.md
./html2myst.py _source_html/BShape.html kits/interface/shape.md
./html2myst.py _source_html/BShapeIterator.html kits/interface/shape-iterator.md
./html2myst.py _source_html/BShelf.html kits/interface/shelf.md
./html2myst.py _source_html/BSimpleGameSound.html kits/game/simple-game-sound.md
./html2myst.py _source_html/BSlider.html kits/interface/slider.md
./html2myst.py _source_html/BSmallBuffer.html kits/media/small-buffer.md
./html2myst.py _source_html/BSoundPlayer.html kits/media/sound-player.md
./html2myst.py _source_html/BStatable.html kits/storage/statable.md
./html2myst.py _source_html/BStatusBar.html kits/interface/status-bar.md
./html2myst.py _source_html/BStreamingGameSound.html kits/game/streaming-game-sound.md
./html2myst.py _source_html/BStringItem.html kits/interface/string-item.md
./html2myst.py _source_html/BStringView.html kits/interface/string-view.md
./html2myst.py _source_html/BSymLink.html kits/storage/sym-link.md
./html2myst.py _source_html/BTab.html kits/interface/tab.md
./html2myst.py _source_html/BTabView.html kits/interface/tab-view.md
./html2myst.py _source_html/BTextView.html kits/interface/text-view.md
./html2myst.py _source_html/BTimeCode.html kits/media/time-code.md
./html2myst.py _source_html/BTimedEventQueue.html kits/media/timed-event-queue.md
./html2myst.py _source_html/BTimeSource.html kits/media/time-source.md
./html2myst.py _source_html/BTranslationUtils.html kits/translation/translation-utils.md
./html2myst.py _source_html/BTranslator.html kits/translation/translator.md
./html2myst.py _source_html/BView.html kits/interface/view.md
./html2myst.py _source_html/BVolume.html kits/storage/volume.md
./html2myst.py _source_html/BVolumeRoster.html kits/storage/volume-roster.md
./html2myst.py _source_html/BWindow.html kits/interface/window.md 
./html2myst.py _source_html/BWindowScreen.html kits/game/window-screen.md
./html2myst.py _source_html/NetworkSockets.html kits/network/network-sockets.md
./html2myst.py _source_html/TheApplicationKit_MessageConstants.html kits/application/message-constants.md
./html2myst.py _source_html/TheGameKit_CardHooks.html kits/game/graphics-card-hook-functions.md
./html2myst.py _source_html/TheGameKit_Constants.html kits/game/constants.md
./html2myst.py _source_html/TheGameKit_DefinedTypes.html kits/game/defined-types.md
./html2myst.py _source_html/TheGameKit_Functions.html kits/game/global-functions.md
./html2myst.py _source_html/TheInputServer_Functions.html kits/input/functions.md
./html2myst.py _source_html/TheInputServer_Messages.html kits/input/message-constants.md
./html2myst.py _source_html/TheInterfaceKit_Functions.html kits/interface/functions.md
./html2myst.py _source_html/TheInterfaceKit_GeneralConstants.html kits/interface/general-constants.md
./html2myst.py _source_html/TheInterfaceKit_MessageConstants.html kits/interface/message-constants.md
./html2myst.py _source_html/TheKernelKit_Areas.html kits/kernel/areas.md
./html2myst.py _source_html/TheKernelKit_Images.html kits/kernel/images.md
./html2myst.py _source_html/TheKernelKit_Miscellaneous.html kits/kernel/miscellaneous.md
./html2myst.py _source_html/TheKernelKit_Ports.html kits/kernel/ports.md
./html2myst.py _source_html/TheKernelKit_Semaphores.html kits/kernel/semaphores.md
./html2myst.py _source_html/TheKernelKit_SystemInfo.html kits/kernel/system-info.md
./html2myst.py _source_html/TheKernelKit_ThreadsAndTeams.html kits/kernel/threads-and-teams.md
./html2myst.py _source_html/TheKernelKit_Time.html kits/kernel/time.md
./html2myst.py _source_html/TheMailDaemon_Functions.html kits/mail/mail-daemon-functions.md
# ./html2myst.py _source_html/The_Node_Monitor.html kits/storage/the-node-monitor.md
