[theme]
inherit = "basic"
stylesheet = "haiku.css"
pygments_style = "autumn"
sidebars = "localtoc.html"

[options]
full_logo         = false
body_min_width    = "59em"
body_max_width    = "70em"
textcolor         = "#333333"
headingcolor      = "#0c3762"
linkcolor         = "#dc3c01"
visitedlinkcolor  = "#dc3c01"
hoverlinkcolor    = "#ff4500"
